//LET AND CONST GIVE REFERENCE ERROR HERE//
// console.log(a);
// console.log(b);
// console.log(c);
//console.log(y);


var a=10;

let b=20;
const c=30;


//SYNTAX ERROR//
// const d=100;
// console.log(d);

// let x=1;
// let x=2;


//TYPE ERROR//
//WHEN WE TRY TO REDEFINE A CONST VARIABLE //
const x=a;
x=b;
console.log(x);


//LET AND CONST ARE IN TEMPORAL DEAD ZONE UNTIL A VALUE TO THE VARIABLE IS NOT ASSIGNED TO THEM//
//LET AND CONST ARE BLOCK SCOPED BUT VAR IS FUNCTION SCOPED//
//CONST CAN'T BE REDIFINED BUT LET AND VAR CAN BE //
//NOT PART OF GLOBAL OBJECT AND IS IN SEPRATE MEMORY SPACE UNTIL VALUE IS NOT ASSIGNED TO -- LET AND CONST AND UNTIL THEN THEY CAN BE ACESS IF DO THEY RETURN REFERENCE ERROR//




